name: flutter_download_manager_dio4
description: Flutter Download Manager is a Cross-Platform file downloader with resumeable, parallel and batch Download support. Also be notified of download status and progress updates
version: 0.5.6
homepage: https://github.com/skyNet2017/flutter_download_manager_dio4

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.1

flutter:

